Pr/backend
leetcode-pp/website pull request #9
Opened 2020-08-08 12:12 UTC by qcl006007

WIP： fix coments

2020-08-10 02:31 UTC, azl397985856 requested changes

2020-08-10 02:31 UTC, azl397985856 commented on server/.gitignore
> +package-lock.json
- why package-lock.json?
- why not root .gitignore

2020-08-10 02:31 UTC, azl397985856 commented on server/README.md
> +npm i --save
1. why --save?
2. that't to say, if I want to run start, should run build first? kind of ...

2020-08-10 02:31 UTC, azl397985856 commented on server/package.json
> +    "start": "node ./dist/app.js",
1. what's the start command in production mode? if it's start, I think background running may be better, such as pm2? also, I found the pm2.json in your code .

2020-08-10 02:31 UTC, azl397985856 commented on server/src/.eslintrc.js
> +module.exports = {
1. same as  .gitignore . There is no need to create a new one

2020-08-10 02:31 UTC, azl397985856 commented on server/src/app.ts
> +    console.info(new Date().toLocaleString());
try to replace the time log statement with  a logger middleware which log the time within each request.

2020-08-10 02:31 UTC, azl397985856 commented on server/src/common/hash.ts
> +const SALT_WORK_FACTOR = 10;
really？ SALT is 10?

2020-08-10 02:31 UTC, azl397985856 commented on server/src/config.ts
> +        uri: 'localhost:27017/website',
1. connection string should be placed in a config file . (also port, logLevel etc)
2. based on 1, different env should use different connection string

2020-08-10 02:31 UTC, azl397985856 commented on server/src/controllers/exercise.controller.ts
> +        let user: any = await User.findOne({_id: _id});
no any , especially user.

2020-08-10 02:31 UTC, azl397985856 commented on server/src/controllers/exercise.controller.ts
> +            code: 1,
code <- config file

2020-08-10 02:31 UTC, azl397985856 commented on server/src/controllers/exercise.controller.ts
> +        let myExercise = await Exercises.findOne({_id: _id, createAt: {$regex: reg}});
same as user

2020-08-10 02:31 UTC, azl397985856 commented on server/src/controllers/exercise.controller.ts
> +const findOfficialExercises = async (ctx, next) => {
1. typescript, not anyscript or no-typing-script

2020-08-10 02:31 UTC, azl397985856 commented on server/src/controllers/user.controller.ts
> +const userSignin = async (ctx, next) => {
prefix user is redundant

2020-08-10 02:31 UTC, azl397985856 commented on server/src/db/index.ts
> +const options = {
options <- config file

double check the rest

2020-08-10 02:31 UTC, azl397985856 commented on server/src/schemas/example.ts
> +import { Schema, model } from 'mongoose';
remove it ?

2020-08-10 02:31 UTC, azl397985856 commented on server/src/schemas/exercise.ts
> +    type: String
given a default value?eg,   uuid

2020-08-10 02:31 UTC, azl397985856 commented on server/tsconfig.json
> +{
put it outside

2020-08-11 08:47 UTC, qcl006007 commented on server/.gitignore
> +package-lock.json
removed  server/.gitignore

package-lock is not used, has been removed

2020-08-11 08:51 UTC, qcl006007 commented on server/README.md
> +npm i --save
fix it ready

2020-08-11 08:52 UTC, qcl006007 commented on server/package.json
> +    "start": "node ./dist/app.js",
yeah, I make pm2.json, yet I do not have much experience of it, will start to use it!

2020-08-11 08:53 UTC, qcl006007 commented on server/src/.eslintrc.js
> +module.exports = {
ok, i understand, use the same with file in the root

2020-08-11 08:54 UTC, qcl006007 commented on server/src/controllers/user.controller.ts
> +const userSignin = async (ctx, next) => {
understand

2020-08-11 08:55 UTC, qcl006007 commented on server/src/schemas/example.ts
> +import { Schema, model } from 'mongoose';
ok, removed

2020-08-11 09:39 UTC, qcl006007 commented on server/src/common/hash.ts
> +const SALT_WORK_FACTOR = 10;
因为我们是手工注册，其实这个加密没用到；
SALT 我不是很懂，下来看一下

2020-08-15 16:03 UTC, qcl006007 commented on server/src/schemas/exercise.ts
> +    type: String
add subject collection: (题目表)，it will be related to subject collection

2020-08-16 01:59 UTC, qcl006007 commented on server/src/schemas/exercise.ts
> +    type: String
add subject collection: (题目表)，it will be related to subject collection

2020-08-16 03:06 UTC, qcl006007 commented on server/src/app.ts
> +    console.info(new Date().toLocaleString());
add morgan middleware to record log

2020-08-16 11:15 UTC, qcl006007 commented on server/tsconfig.json
> +{
tsconfig put outside? when run build ,it will not find this config

2020-08-16 11:39 UTC, qcl006007 commented on server/src/controllers/exercise.controller.ts
> +            code: 1,
后端再改吧。。

2020-08-16 11:40 UTC, qcl006007 commented on server/src/controllers/exercise.controller.ts
> +        let myExercise = await Exercises.findOne({_id: _id, createAt: {$regex: reg}});
不少地方没加 type ，用User 好像也报问题； 我想着有时间统一加一批吧

2020-08-16 11:41 UTC, qcl006007 commented on server/src/controllers/exercise.controller.ts
> +const findOfficialExercises = async (ctx, next) => {
捂脸 见人； 明白，不过还是 anycript 写的舒服

2020-08-19 11:38 UTC, azl397985856 requested changes
1. using github secret
2. config eg: src/development.config.js

2020-08-30 06:25 UTC, azl397985856 approved these changes

2020-08-30 06:54 UTC, merged